# Generated by Django 5.2 on 2025-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='theater_id',
            new_name='theater',
        ),
        migrations.RenameField(
            model_name='showtimes',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='showtimes',
            old_name='theater_id',
            new_name='theater',
        ),
    ]
