# Generated by Django 5.2 on 2025-04-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_table_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_table',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
