# Generated by Django 5.2 on 2025-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('mystery', 'Mystery'), ('family', 'Family'), ('musical', 'Musical'), ('western', 'Western')], max_length=255)),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('tamil', 'Tamil'), ('kannada', 'Kannada'), ('telugu', 'Telugu'), ('hindi', 'Hindi'), ('french', 'French'), ('german', 'German'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('portuguese', 'Portuguese'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('italian', 'Italian'), ('dutch', 'Dutch')], max_length=255)),
                ('synopsis', models.TextField()),
                ('cast', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('thriller_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
