# Generated by Django 5.2 on 2025-04-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_image',
        ),
    ]
