# Generated by Django 5.2 on 2025-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
