# Generated by Django 5.2 on 2025-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_movies_by_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=1000)),
            ],
        ),
    ]
