# Generated by Django 5.2 on 2025-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_search_movies_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_movies_by_name',
            name='moviename',
            field=models.CharField(max_length=2000),
        ),
    ]
